# ****************************************
# Nanshan 服务
# Spring zuul 配置文件
# 20180224
# ****************************************

spring:
  application:
    name: nanshan-gateway

server:
  port: 5555

# zuul routes
zuul:
  routes:
    api-path: /nanshan/**
    zuul.routes.api.serviceId: nanshan-service
    #api-b.path: /nanshan-B/**
    #api-b.serviceId: nanshan-service-B

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/